human_viral_fusion: "~/Tools/GRCh38_hiv.fa" #hg38+hiv fasta file

human_index: "~/hisat_hiv/hg38" # hisat2 index for human genome

viral_index: "~/hisat_hiv/hivref" # hisat2 index for hiv genome

threads_for_alignment: 20 # how many threads should be used for 
